import math

# SETTINGS
GRAPH_TIME_RANGE = 5

CALIB_ANGLE_OFFSET = 2.05

# # BASE DEFINITION
# DIST_BETWEEN_ADJACENT_ARMS_MM = 64.0
# DIST_FROM_CENTER_TO_MOTOR_AXIS_MM = 90.0

# DIST_FROM_FLOOR_TO_MOTOR_AXIS_MM = 40.0

# # ARM DEFINITION
# DIST_FROM_ARM_AXIS_TO_BALL_JOINT_MM = 155.24175

# # ROD DEFINITION
# DIST_BETWEEN_EACH_BALL_JOINT_MM = 215.83

# # TOOLHEAD DEFINITION
# DIST_BETWEEN_ADJACENT_BALL_JOINTS_MM = 64.0
# DIST_FROM_CENTER_TO_BALL_JOINT_AXIS_MM = 107.3

# DIST_FROM_TOOLHEAD_CENTER_TO_BALL_JOINT_PLANE_MM = 5.0




# BASE DEFINITION
DIST_BETWEEN_ADJACENT_ARMS_MM = 64.0
DIST_FROM_CENTER_TO_MOTOR_AXIS_MM = 90.0

DIST_FROM_FLOOR_TO_MOTOR_AXIS_MM = 40.0

# ARM DEFINITION
DIST_FROM_ARM_AXIS_TO_BALL_JOINT_MM = 155.24175

# ROD DEFINITION
DIST_BETWEEN_EACH_BALL_JOINT_MM = 215.83

# TOOLHEAD DEFINITION
DIST_BETWEEN_ADJACENT_BALL_JOINTS_MM = 139.545
DIST_FROM_CENTER_TO_BALL_JOINT_AXIS_MM = 69.1592

DIST_FROM_TOOLHEAD_CENTER_TO_BALL_JOINT_PLANE_MM = 60